$ANSIBLE_VAULT;1.1;AES256
34383939376633633463663565336362346437376433353064303966623466663061666435336333
6430323264333332363765303534323265366234353333300a666537663535616430383238623635
64356434623038613162633666356433333562386266323036393638656461666635336639623131
6639616236376463360a323736626139333539303430656661623237656533313535333965393131
65633237343336333930373365643365323432646161643132643531373235656566323562656562
38383538333461646662313437646338356231346366636130633665663166336131313038633833
63363930626431383337666638353865353531326134313834313164333237646638643638653832
64363732663134626239653534393930643534626135646532316235613063303137623762353061
35663535333434373038363732343565373231303963313764633064643030343031316262653662
66666562336138653364326264366337666234393165663764653461656633613239376536333330
31666435343338306162356138333738633563313738656265316465613765396136373339396434
65383932393737306566663932633731656133323937646436633836396233383866653237383635
38396238336235613536656431626332336639326461353339363230363636333238
