$ANSIBLE_VAULT;1.1;AES256
36373638646630663135626361383436613332613539613661363931626132656234333530303966
3232373635393231636362343933343062313839386139330a366166376466303133306639666337
36623563613862313362623031643335396530663330656262333463613034666139353832326438
3032333832646162660a303062626239363864666134616436636634313635323833666338643062
35323630383933613764343935613662396466613966383931663137663137663232363634653434
65633461373339323364363536303564376333343963303363343733306563313131386233383130
643632666166386632623065356333393133
